### ISSUE TITLE
specify in the truthy/falsy chapter that there are only 6 types of falsey and the rest are truthy

### ISSUE THREAD

**Issue by lizparody** [MrPowers/code_quizzer#10]
section http://www.codequizzes.com/javascript-book/truthy-falsy you should specify that there is only 6 types of falsey, "undefined, NaN, null, 0, " ", and false" and the rest are thruty.

**Comment by MrPowers** [comment]
@lizparody - Great point :tada: 

I [updated the chapter](https://github.com/MrPowers/code_quizzer/commit/3bc60767f4355ef51d549db65c3859b8d551d50f).  Thanks!
