### ISSUE TITLE
change order of chapters

### ISSUE THREAD

**Issue by lizparody** [MrPowers/code_quizzer#11]
this three chapters http://www.codequizzes.com/javascript-book/infinity-nan
http://www.codequizzes.com/javascript-book/truthy-falsy
http://www.codequizzes.com/javascript-book/and-or-operators
should be before "introduction to objects" because objects are harder than this.

**Comment by MrPowers** [comment]
I [updated the order](http://www.codequizzes.com/javascript-book) and now all these sections come before Introduction to Objects.  Thanks!!
