### ISSUE TITLE
First problem of "Loops with if" chapter doesn't work

### ISSUE THREAD

**Issue by lizparody** [MrPowers/code_quizzer#13]
It should be like this:

function joinIfString(array){
var result = "";
for(var i =0; i < array.length; i++){
if(typeof(array[i])== "string"){
result += array[i];
}
}
return(result);
}
var planet = ["earth", "fire", 34, undefined, "wind", [], "water"];
var r = joinIfString(planet);         // you have (arr) here which is not defined
console.log(r);

**Comment by MrPowers** [comment]
@lizparody - You can add syntax highlighting to your post like this: https://help.github.com/articles/github-flavored-markdown/#syntax-highlighting

Make sure to always use syntax highlighting on GitHub and StackOverflow!

**Comment by MrPowers** [comment]
I fixed the bug with [this commit](https://github.com/MrPowers/code_quizzer/commit/67cf01843f2a509b69ad8f4999c93b31e098dd32).  Thanks!
