### ISSUE TITLE
Typo error on Main Page - Teaching Philosophy

### ISSUE THREAD

**Issue by Rey810** [MrPowers/code_quizzer#67]
Hi! :) I haven't contributed before but noticed some typos on the 6th bullet point of the Teaching Philosophy. Can I submit a pull request to fix them?

**Comment by MrPowers** [comment]
@Rey810 - Yep, definitely send a PR and I'll get it merged in ;)

**Comment by Rey810** [comment]
Great! I'll do so now.

**Comment by MrPowers** [comment]
Merged in this fix, thanks for the help!
