### ISSUE TITLE
Edit Account

### ISSUE THREAD

**Issue by thelastinuit** [MrPowers/code_quizzer#7]
When I try to edit my account (gear link), it says the page doesn't exist.

<i class="fa fa-gear" data-toggle="tooltip" data-placement="bottom" title="Edit Account"></i>
route: http://www.codequizzes.com/users/edit

**Comment by MrPowers** [comment]
Thanks, I'll look into this in the next couple of days.  I really appreciate you opening up the issue!  :+1:

**Comment by thelastinuit** [comment]
Love the site :)

Help with what I can :)

**Comment by MrPowers** [comment]
I pushed up a silly little fix that should solve the problem: https://github.com/MrPowers/code_quizzer/commit/f6b306c384766e7e222b0f7536b7a70e6d91a1c3

Can you please try the link again and let me know if it's working for you? :smile: 

Sorry for taking so long to get this fixed.

**Comment by thelastinuit** [comment]
SUCCESS!
